/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ScoresRouteImport } from './routes/scores'
import { Route as LiveRouteImport } from './routes/live'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LiveIndexRouteImport } from './routes/live.index'
import { Route as LiveCampaignIdRouteImport } from './routes/live.$campaignId'

const ScoresRoute = ScoresRouteImport.update({
  id: '/scores',
  path: '/scores',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveRoute = LiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveIndexRoute = LiveIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LiveRoute,
} as any)
const LiveCampaignIdRoute = LiveCampaignIdRouteImport.update({
  id: '/$campaignId',
  path: '/$campaignId',
  getParentRoute: () => LiveRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/live': typeof LiveRouteWithChildren
  '/scores': typeof ScoresRoute
  '/live/$campaignId': typeof LiveCampaignIdRoute
  '/live/': typeof LiveIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/scores': typeof ScoresRoute
  '/live/$campaignId': typeof LiveCampaignIdRoute
  '/live': typeof LiveIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/live': typeof LiveRouteWithChildren
  '/scores': typeof ScoresRoute
  '/live/$campaignId': typeof LiveCampaignIdRoute
  '/live/': typeof LiveIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/live' | '/scores' | '/live/$campaignId' | '/live/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/scores' | '/live/$campaignId' | '/live'
  id: '__root__' | '/' | '/live' | '/scores' | '/live/$campaignId' | '/live/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LiveRoute: typeof LiveRouteWithChildren
  ScoresRoute: typeof ScoresRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/scores': {
      id: '/scores'
      path: '/scores'
      fullPath: '/scores'
      preLoaderRoute: typeof ScoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live': {
      id: '/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof LiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live/': {
      id: '/live/'
      path: '/'
      fullPath: '/live/'
      preLoaderRoute: typeof LiveIndexRouteImport
      parentRoute: typeof LiveRoute
    }
    '/live/$campaignId': {
      id: '/live/$campaignId'
      path: '/$campaignId'
      fullPath: '/live/$campaignId'
      preLoaderRoute: typeof LiveCampaignIdRouteImport
      parentRoute: typeof LiveRoute
    }
  }
}

interface LiveRouteChildren {
  LiveCampaignIdRoute: typeof LiveCampaignIdRoute
  LiveIndexRoute: typeof LiveIndexRoute
}

const LiveRouteChildren: LiveRouteChildren = {
  LiveCampaignIdRoute: LiveCampaignIdRoute,
  LiveIndexRoute: LiveIndexRoute,
}

const LiveRouteWithChildren = LiveRoute._addFileChildren(LiveRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LiveRoute: LiveRouteWithChildren,
  ScoresRoute: ScoresRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
